config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get "/home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :edit,  :update, :destroy]
  resources :users, only: [:create, :index, :show, :edit, :update]
  #get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user
   validates :title, presence: true
   validates :body, presence: true, length: {maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, length: {minimum: 2, maximum: 20 }, uniqueness:true
  validates :introduction, length: {maximum: 50 }

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_in_path_for(resource)
    @user = current_user
    user_path(@user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] = "You have created book successfully."
       redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    user_id = Book.find(params[:id]).user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to books_path
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book_new = Book.new
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
     user_id = params[:id].to_i
     login_user_id = current_user.id
     if(user_id != login_user_id)
       redirect_to user_path(current_user)
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h1>User info</h1>

<%= image_tag user.get_profile_image(100,100) %>
<div>name:<%= user.name %></div>
<div>introduction:<%= user.introduction %></div>

<%= link_to edit_user_path(user),class: "btn btn-outline-secondary btn-block" do %>
<i class="fas fa-user-cog"></i>
<% end %>

<h1>New book</h1>
<%= form_with model: book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <%= @book.errors.count %> errors prohibited this book from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @book do |f| %>

      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, autofocus: true, id:"book_title", placeholder:"title", class: "form-control book_title" %>
      </div>

      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, autofocus: true, class: "form-control book_body" %>
      </div>

      <div class="form-group">
        <button class="btn btn-success" type="submit">Update Book</button>
      </div>

      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div id="error_explanation">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'book', book: @book,user: @user  %>
    </div>

    <div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th class="header1"></th>
      <th class="header2">Title</th>
      <th class="header3">Opinion</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
      </td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
    </tr>
  <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'book',  book: @book_new ,user: @book.user %>
    </div>
    <div class="col-md-8 offset-md-1">
<h1>Book detail</h1>
<table class="table">
  <tbody>
    <tr>
      <td><%= link_to user_path(@book.user.id) do %>
          <%= image_tag @book.user.get_profile_image(100, 100) %><br>
          <%= @book.user.name %>
          <% end %>
      </td>
      <td><%= link_to book_path(@book.id) do %>
          <%= @book.title %>
          <% end %>
      </td>
      <td><%= @book.body %></td>
      <% if @book.user == current_user %>
      <td><%= link_to "Edit", edit_book_path(@book) , class: 'btn btn-sm btn-success' %></td>
      <% end %>
      <% if @book.user == current_user %>
      <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-sm btn-danger' %></td>
      <% end %>
    </tr>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
Footer

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/7d4686f8ad.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i>
                    Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i>
                    Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i>
                    Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>
                    Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i>
                    Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <p id="notice"><%= flash[:notice] %></p>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>error prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @user do |f| %>

      <div class="form-group">
        <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name" %>
      </div>

      <div class="form-group">
        <label for="inputImage">Image</label>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*", class: "form-control-file user_image" %>
      </div>

      <div class="form-group">
        <label for="inputIntroduction">Introduction</label>
        <%= f.text_area :introduction, autofocus: true, class: "form-control introduction" %>
      </div>

      <div class="form-group">
        <button class="btn btn-secondary" type="submit">Update User</button>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/book', book: @book,user: @user  %>
    </div>

    <div class="col-md-8 offset-md-1">
<h1>Users</h1>
<table class="table">
  <thead>
    <tr>
      <th class="header1">image</th>
      <th class="header2">name</th>
      <th class="header3"></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(100,100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", user_path(user) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/book', book: @book_new ,user: @user  %>
    </div>
    <div class="col-md-8 offset-md-1">
<h1>Books</h1>
<table class="table">
  <thead>
    <tr>
      <th class="header1"></th>
      <th class="header2">Title</th>
      <th class="header3">Opinion</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to user_path(@user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
      </td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
    </tr>
  <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>